[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.13.1"  # Current LTS version that works with Next.js 15
  SECRETS_SCAN_OMIT_KEYS = "GOOGLE_SERVICE_ACCOUNT_KEY,SPREADSHEET_ID,NEXT_PUBLIC_THIRDWEB_CLIENT_ID,GOOGLE_SERVICE_ACCOUNT_EMAIL"